In [3]:
import tensorflow as tf

n_inputs = 3
n_neurons = 5

X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons], dtype=tf.float32))
Wy = tf.Variable(tf.random_normal(shape=[n_neurons, n_neurons], dtype=tf.float32))
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32))

Y0 = tf.tanh(tf.matmul(X0, Wx) + b)
Y1 = tf.tanh(tf.matmul(Y0, Wy) +tf.matmul(X1, Wx) + b)

init = tf.global_variables_initializer()



In [5]:
import numpy as np

X0_batch =  np.array([[0,1,2], [3,4,5], [6,7,8],[9,0,1]])
X1_batch =  np.array([[9,8,7], [0,0,0], [6,5,4],[3,2,1]])

with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict={X0: X0_batch, X1: X1_batch})

In [6]:
print(Y0_val)

[[ 0.99845159 -0.85170346  0.80836195  0.14894362  0.83997458]
 [ 0.99999958 -0.98771256 -0.40707266  0.6692903   0.99985379]
 [ 1.         -0.99904615 -0.96305966  0.89935839  1.        ]
 [-0.99982816  0.45454979 -0.99999988 -0.94727069  0.99245626]]


In [7]:
print(Y1_val)

[[ 0.99999934 -0.99665815 -0.99999952  0.96099669  1.        ]
 [-0.83831775  0.01317022 -0.87209904  0.9911024  -0.98769242]
 [ 0.99596685 -0.74578577 -0.99994862  0.99989009  0.94533247]
 [-0.17974246 -0.21842025 -0.73548651  0.89333916 -0.09595203]]


In [8]:
tf.reset_default_graph()

n_inputs = 3
n_neurons = 5

X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
output_seqs, states = tf.contrib.rnn.static_rnn(basic_cell, [X0, X1], dtype=tf.float32)
Y0, Y1 = output_seqs

init = tf.global_variables_initializer()

In [9]:

X0_batch =  np.array([[0,1,2], [3,4,5], [6,7,8],[9,0,1]])
X1_batch =  np.array([[9,8,7], [0,0,0], [6,5,4],[3,2,1]])

with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict={X0: X0_batch, X1: X1_batch})

In [10]:
print(Y0_val)

[[ 0.5974412   0.17399774  0.82298547  0.70208305  0.29244471]
 [ 0.96385115 -0.96691579  0.99354988  0.99863613 -0.77203685]
 [ 0.99731451 -0.99960196  0.99978441  0.99999487 -0.98204261]
 [ 0.9822008  -0.99997342 -0.84734464  0.99829781 -0.99989569]]


In [11]:
print(Y1_val)

[[ 0.99589062 -0.99999809  0.99917483  0.99999577 -0.99852717]
 [-0.03342348  0.52578479  0.80908817 -0.79165     0.59691805]
 [ 0.96492207 -0.99932218  0.99821913  0.99834836 -0.97994876]
 [ 0.7961694  -0.54813963  0.79524148  0.94226551 -0.94740754]]


In [12]:
tf.reset_default_graph()

n_steps = 2
n_inputs = 3
n_neurons = 5

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
X_seqs = tf.unstack(tf.transpose(X, perm=[1, 0, 2]))

basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
output_seqs, states = tf.contrib.rnn.static_rnn(basic_cell, X_seqs, dtype=tf.float32)
outputs = tf.transpose(tf.stack(output_seqs), perm=[1, 0, 2])

init = tf.global_variables_initializer()

In [13]:
X_batch = np.array([
        # t = 0      t = 1 
        [[0, 1, 2], [9, 8, 7]], # instance 1
        [[3, 4, 5], [0, 0, 0]], # instance 2
        [[6, 7, 8], [6, 5, 4]], # instance 3
        [[9, 0, 1], [3, 2, 1]], # instance 4
    ])

with tf.Session() as sess:
    init.run()
    outputs_val = outputs.eval(feed_dict={X: X_batch})

In [14]:
print(np.transpose(outputs_val, axes=[1, 0, 2])[1])

[[-1.         -0.99999988 -0.99817824  1.          0.61666083]
 [ 0.28097793 -0.69652265 -0.41010007  0.29946113  0.23089793]
 [-0.99999988 -0.99998862 -0.98018324  0.99998349  0.37570328]
 [-0.9949668  -0.98993248 -0.66498721  0.97867668  0.16196707]]


In [15]:
print(outputs_val)

[[[-0.91208279 -0.3208991  -0.14383808  0.9445861  -0.33042395]
  [-1.         -0.99999988 -0.99817824  1.          0.61666083]]

 [[-0.99999559 -0.99582613 -0.82933086  0.9999634  -0.38062185]
  [ 0.28097793 -0.69652265 -0.41010007  0.29946113  0.23089793]]

 [[-1.         -0.99998307 -0.97700971  1.         -0.42867255]
  [-0.99999988 -0.99998862 -0.98018324  0.99998349  0.37570328]]

 [[-0.99996656 -0.99999154 -0.99994975  0.4894594   0.96123618]
  [-0.9949668  -0.98993248 -0.66498721  0.97867668  0.16196707]]]


In [19]:
from tensorflow.examples.tutorials.mnist import input_data

n_steps= 28
n_inputs= 28
mnist = input_data.read_data_sets("/tmp/data")
print(mnist.test.images.shape)
X_test = mnist.test.images.reshape((-1, n_steps, n_inputs))
print(X_test.shape)
y_test = mnist.test.labels

Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
(10000, 784)
(10000, 28, 28)


In [20]:
tf.reset_default_graph()

n_steps = 28
n_inputs = 28
n_neurons = 150
n_outputs = 10

learning_rate = 0.001

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
y = tf.placeholder(tf.int32, [None])

with tf.variable_scope("rnn", initializer=tf.contrib.layers.variance_scaling_initializer()):
    basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons, activation=tf.nn.relu)
    outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32)

logits = tf.layers.dense(states, n_outputs)
xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y, logits=logits)
loss = tf.reduce_mean(xentropy)
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(loss)
correct = tf.nn.in_top_k(logits, y, 1)
accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))

init = tf.global_variables_initializer()

In [21]:
n_epochs = 100
batch_size = 150

with tf.Session() as sess:
    init.run()
    for epoch in range(n_epochs):
        for iteration in range(mnist.train.num_examples // batch_size):
            X_batch, y_batch = mnist.train.next_batch(batch_size)
            X_batch = X_batch.reshape((-1, n_steps, n_inputs))
            sess.run(training_op, feed_dict={X: X_batch, y: y_batch})
        acc_train = accuracy.eval(feed_dict={X: X_batch, y: y_batch})
        acc_test = accuracy.eval(feed_dict={X: X_test, y: y_test})
        print(epoch, "Train accuracy:", acc_train, "Test accuracy:", acc_test)

0 Train accuracy: 0.933333 Test accuracy: 0.9271
1 Train accuracy: 0.94 Test accuracy: 0.9466
2 Train accuracy: 0.946667 Test accuracy: 0.9552
3 Train accuracy: 0.98 Test accuracy: 0.9597
4 Train accuracy: 0.98 Test accuracy: 0.9663
5 Train accuracy: 0.966667 Test accuracy: 0.9665
6 Train accuracy: 0.96 Test accuracy: 0.9684
7 Train accuracy: 0.986667 Test accuracy: 0.9708
8 Train accuracy: 0.98 Test accuracy: 0.9745
9 Train accuracy: 0.966667 Test accuracy: 0.9722
10 Train accuracy: 0.986667 Test accuracy: 0.9694
11 Train accuracy: 1.0 Test accuracy: 0.9778
12 Train accuracy: 0.966667 Test accuracy: 0.9689
13 Train accuracy: 0.993333 Test accuracy: 0.9733
14 Train accuracy: 0.966667 Test accuracy: 0.9751
15 Train accuracy: 0.98 Test accuracy: 0.9754
16 Train accuracy: 0.98 Test accuracy: 0.9771
17 Train accuracy: 0.966667 Test accuracy: 0.9757
18 Train accuracy: 0.986667 Test accuracy: 0.9756
19 Train accuracy: 0.973333 Test accuracy: 0.9731
20 Train accuracy: 0.993333 Test accuracy: 

KeyboardInterrupt: 